// Generated by https://quicktype.io

export interface DashboardSummaryResponse {
    numberOfClients:         number;
    numberOfProducts:        number;
    productsWithNoInventory: number;
    lowInventory:            number;
}
